added init command to add developer key & secret

diff --git a/goodreads b/goodreads
--- a/goodreads
+++ b/goodreads
@@ -22,13 +22,33 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-USER_DEVELOPER_KEY="DEVELOPER_KEY=\"\""
 USER_CONFIG_FILE="$HOME/.goodreads.conf"
-if ! [[ -f "$USER_CONFIG_FILE" ]]; then
-    touch "$USER_CONFIG_FILE"
-    echo -e "$USER_DEVELOPER_KEY" > "$USER_CONFIG_FILE"
-fi
-source "$USER_CONFIG_FILE"
+
+function init_script() {
+    if [[ $# -eq 0 ]]; then
+        if ! [[ -f "$USER_CONFIG_FILE" ]]; then
+            echo "Cannot find developer keys"
+        else
+            source "$USER_CONFIG_FILE"
+        fi
+    else
+        show_help;
+    fi
+}
+
+function add_keys() {
+    dev_key=$1
+    secret=$2
+    if ! [[ -f "$USER_CONFIG_FILE" ]]; then
+        touch "$USER_CONFIG_FILE"
+        echo "DEVELOPER_KEY=$dev_key" > "$USER_CONFIG_FILE"
+        echo "GOOD_SECRET=$secret" >> "$USER_CONFIG_FILE"
+        # TODO: Make an initial request to check validation
+    else
+        cat $USER_CONFIG_FILE
+    fi
+
+}
  
 function show_help () {
     echo "Usage: "
@@ -38,6 +58,7 @@ function show_help () {
     echo "  book:     book related options"
     echo "  author:   author related options"
     echo "  user:     user related options"
+    echo "  init:     initialize goodreadsh"
     echo "  help:     show help message"
     echo
     echo "Enter \`goodreads <option> help\` for more."
@@ -47,6 +68,8 @@ if [[ $# = 0 ]]; then
     show_help;
     exit
 fi
+
+init_script;
 
 arg=$1
 case $arg in
@@ -229,6 +252,37 @@ case $arg in
 
             esac
             ;;
+
+    init )
+        #echo "$1 $2 $3 $4 $5"
+        if [[ "$#" -ge 2 ]]; then
+            is_dev_key_set=false
+            is_secret_set=false
+            if [[ "$2" == "--dev-key" ]]; then
+                is_dev_key_set=true
+                echo "Developer Key is: $3";
+            fi
+
+            if [[ "$4" == "--secret" ]]; then
+                is_secret_set=true
+                echo "Secret is: $5";
+            fi
+
+            if [[ $is_dev_key_set ]] && [[ $is_secret_set ]]; then
+                echo "Setting Dev key to $3 and Secret to $3";
+                add_keys "$3" "$5"
+            else
+                echo "Please specify missing keys"
+            fi
+
+        else
+            echo "goodreadsh requires your developer key in order to use the goodreads API, obtaining one is fairly trivial."
+            echo "Get your API keys here: https://www.goodreads.com/api/keys and again run this init command like:"
+            echo "Usage:"
+            echo "  goodreads init --dev-key [key] --secret [secret]"
+        fi
+
+        ;;
 
     help|h )
         show_help;
